version: '3.9'

services:
  torchserve:
    build:
      dockerfile: ./Dockerfile
    command: torchserve --start --model-store model-store --models all --ts-config /home/model-server/config.properties --ncs
    expose:
      - 8080
      - 8081
      - 8082
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"

  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - torchserve